version: '3.1'

services:
  javeats_app:
    container_name: javeats_restaurant_management_system
    build: .
    ports:
      - "9090:9090"
  javeats_lites_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
