version: '3.1'

services:
  javeats_lites_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: javeats_lites
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
