server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/javeats_lites
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      continue-on-error: false
      mode: always
      schema-locations: 'classpath:sql/schema-*.sql'
      separator: '/'


